* Fall 2020 - Lab 05

* Last name:Mok

* First name:Adrian

* GitHub username:Adrian-Mok15

* Notes: I would set up a refractor where it would be opening up the the file. For all of the functions we wrote, they all opened up the same file, so it would be a lot cleaner if the refractor took in the file name and just opened the file and named it fin. Depending on if the coder wishes to use declare the other variables that aren't used for that specific function, they could also declare westEl and the other variables that may or may not be used.



* General instructions:
- Fill in your name and GitHub username on top.
- Use the Notes section to add any notes to the instructor.
- The main lab description can be found here:
  https://maryash.github.io/135/labs/lab_05.html 


* Specific instructions for lab 05

This lab requires that you implement doctest based tests. There is
already a skeleton ~Makefile~ with targets for ~main~ and ~tests~ as
well as skeleton ~.c~ ~.h~ and ~doctest.h~ files. 

For each function specified in the main lab, add the code to ~funcs.h~
and ~funcs.cpp~. You should call them from ~main~ but you also need to
put in tests into ~tests.cpp~. 

I will test ~main~ but will only consider ~tests.cpp~ to determine if
your functions area all working properly. You will have to make
sensible decisions based on the assignment as to how many tests you
need and what you should test for.

For reference, the doctest package and documentation can be found
[[https://github.com/onqtam/doctest][here]].



*Note:* Remember that your program (including tests) should not ask
 for any keyboard input. When run it should clearly show that all
 tasks are implemented and work.



